### PR TITLE
Cuphead - Add IL auto-reset, and set to game time

### PR DESCRIPTION
**Pull request by mitchell-merry**
This patch adds a couple QoL features + some logging

### CODE REVIEW

**Comment by ero-qt** [comment]
I do not approve of logs being uncommented in the final file shipped to users. It can impact performance.

**Comment by mitchell-merry** [comment]
Which logs? They only log on events like start/split/reset. Your original ASL had similar logs uncommented.

Not to mention the ASL library doing tons of logging on load

**Comment by ero-qt** [comment]
Please review my changes.

**Review by mitchell-merry — COMMENTED** [review]
Looks fine

Edit: I was mistaken - there was an issue.

**Comment by mitchell-merry** [comment]
Added a clause to only fire reset{} when the user is in IL mode (currently being determined by single split & both `ilStart` and `ilEnd` being selected). Should fix that concern about runners doing full runs with a single split as well, or at least mitigate it.

**Comment by mitchell-merry** [comment]
ilEnter should only start the timer when in IL mode - extracted that value and fixed that condition in start{}.

Please review these changes, should be good.

**Pull request merged**
